# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inline_ordering_position', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('format', models.PositiveSmallIntegerField(choices=[(0, 'Open Ended'), (1, 'Choose One'), (2, 'Choose Multiple')])),
            ],
            options={
                'ordering': ('inline_ordering_position',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionResponseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inline_ordering_position', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_response_options', to='rest_surveys.SurveyQuestion')),
            ],
            options={
                'ordering': ('inline_ordering_position',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_surveys.SurveyQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inline_ordering_position', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rest_surveys.Survey')),
            ],
            options={
                'ordering': ('inline_ordering_position',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='response_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_surveys.SurveyResponseOption'),
        ),
        migrations.AddField(
            model_name='surveyquestionresponseoption',
            name='response_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_response_options', to='rest_surveys.SurveyResponseOption'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='response_options',
            field=models.ManyToManyField(blank=True, through='rest_surveys.SurveyQuestionResponseOption', to='rest_surveys.SurveyResponseOption'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rest_surveys.SurveyStep'),
        ),
    ]
